#Shamelessly copied from the Project Euler project
Meteor.startup ->
  if Problems.find().count() is 0
    Problems.insert
      title: "1"
      solution: "233168"
      answers: []
      draft: false
      activeFrom: new Date
      description: "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000."

    Problems.insert
      title: "2"
      solution: "4613732"
      answers: []
      draft: false
      activeFrom: new Date
      description: "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."

    Problems.insert
      title: "3"
      solution: "test"
      answers: []
      draft: false
      activeFrom: new Date
      description: "Svaret er 'test'"

    Problems.insert
      title: "4"
      solution: "test"
      answers: []
      draft: true
      activeFrom: new Date
      description: "Dette er en kladd"

  # If we only have one user. Make him admin!
  if Meteor.users.find().count() is 1
    Meteor.users.update {}, {$set: {isAdmin: true}}

